Upgrade to GCC 14 for macOS UBSAN ci.
Newer versions of macOS SDK throw _bounds.h error with GCC 13.4 when
installed from homebrew.

/opt/homebrew/Cellar/gcc@13/13.4.0/lib/gcc/13/gcc/aarch64-apple-darwin24/13/include-fixed/_stdio.h:78:10: fatal error: _bounds.h: No such file or directory
   78 | #include <_bounds.h>